# Generated by Django 3.2.7 on 2021-11-19 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=20)),
                ('hostel_location', models.CharField(max_length=20)),
                ('hostel_image', models.ImageField(upload_to='')),
                ('hostel_description', models.TextField()),
                ('hostel_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.block')),
                ('hostel_caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.caretaker')),
                ('hostel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.hostel_manager')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room'),
        ),
    ]
